# First remove *all* keybindings
# unbind-key -a
# Now re-insert all the regular tmux keys

# Lazygit use c-k/c-j to move commits up/down
# Source: https://github.com/jesseduffield/lazygit/discussions/3201
# bind -n C-j if-shell "[ #{pane_current_command} = lazygit ]" "send-keys C-j"  "select-pane -D"
# bind -n C-k if-shell "[ #{pane_current_command} = lazygit ]" "send-keys C-k"  "select-pane -U"

# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c '#{pane_current_path}'

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind p
bind -r C-h previous-window
unbind n
bind -r C-l next-window

unbind M-u
unbind O
bind O run-shell '~/.config/tmux/plugins/tpm/bindings/clean_plugins'

unbind M-p
unbind P

# Resize panes
bind -r H resize-pane -L 5     # Resize pane left
bind -r J resize-pane -D 5     # Resize pane down
bind -r K resize-pane -U 5     # Resize pane up
bind -r L resize-pane -R 5     # Resize pane right

# bind-key c confirm-before kill-pane
# bind-key x confirm-before kill-session

# Join-pane
# Format:
#   h|v s|t <src/tgt>
#
# Examples:
#   v t dev:6
#   h s work:docs
#   h t 7
#   v s duo:3
# ------------------------------------------------------

bind-key C-j command-prompt -p "join-pane: h|v s|t <src/tgt>" \
"run-shell \"sh -c 'eval \\\"set -- \\\$1\\\"; layout=\\\$1; mode=\\\$2; loc=\\\$3; \
if [ \\\$# -ne 3 ]; then \
  tmux display-message \\\"Use: h|v s|t <src/tgt>\\\"; \
elif [ \\\"\\\$layout\\\" != \\\"h\\\" ] && [ \\\"\\\$layout\\\" != \\\"v\\\" ]; then \
  tmux display-message \\\"First value must be h or v\\\"; \
elif [ \\\"\\\$mode\\\" != \\\"s\\\" ] && [ \\\"\\\$mode\\\" != \\\"t\\\" ]; then \
  tmux display-message \\\"Second value must be s or t\\\"; \
else \
  tmux join-pane -\\\$layout -\\\$mode \\\"\\\$loc\\\"; \
fi' sh '%%'\""

# Zooming out the current pane
unbind z
bind -r m resize-pane -Z

# Direct layout controls
bind-key e select-layout even-vertical # Equal-width side-by-side panes
bind-key q select-layout even-horizontal # Equal-height top-to-bottom panes
bind-key z select-layout tiled # Balanced grid
bind-key v select-layout main-vertical # Main pane on the left, others on the right
bind-key V select-layout main-vertical-mirrored # Main pane on the right, others on the left
bind-key a select-layout main-horizontal # Main pane on the top, others below
bind-key A select-layout main-horizontal-mirrored # Main pane on the bottom, others above

# bind key for shells
bind-key -r b run-shell "tmux neww ~/Developer/scripts/ephemeral-sesh-manager.sh"

# Focus panes
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Copy mode bindings
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd2Pane # don't exit copy mode when dragging with mouse
